### PR TITLE
use binding_of_caller for JRuby

### PR DESCRIPTION
**Pull request by mmcfarland-cavulus**
for issue #49

### CODE REVIEW

**Comment by sue445** [comment]
Add `jruby` to `.travis.yml`

c.f. https://docs.travis-ci.com/user/languages/ruby/#specifying-ruby-versions-and-implementations

**Comment by mmcfarland-cavulus** [comment]
I guess this is a little more in depth; there is some code that explicitly references the BindingNinja constant. I wonder if it would be worth refactoring that library to give it API-parity with binding_of_caller.

**Comment by joker1007** [comment]
2 is better.
I think so.
I guess that I can implement a code branching for binding_of_caller at `table_syntax.rb`

**Comment by joker1007** [comment]
binding_ninja will support jruby soon.

**Comment by joker1007** [comment]
I have already released v0.4.2 that is supported JRuby.

**Pull request closed without merging**
